version: "3"

services:

  web:
    container_name: rover
    build: ${PWD}/docker-image/.
    image: rover
    volumes:
      - ${PWD}/../rover:/var/www/rover
      - ${PWD}/docker-container-config-files/sites/rover.com:/etc/nginx/sites-enabled/rover.com
      - ${PWD}/docker-container-config-files/xdebug/xdebug.ini:/etc/php/7.2/mods-available/xdebug.ini
    networks:
      rover_subnet:
        ipv4_address: ${ROVER_CONTAINER_IP}
    extra_hosts:
      - ${ROVER_DOMAIN}:127.0.0.1

  mysql:
    container_name: rover-mysql-server
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROVER_MYSQL_ROOT_PASSWORD}
    networks:
      rover_subnet:
        ipv4_address: ${MYSQL_CONTAINER_IP}

networks:
  rover_subnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${ROVER_SUBNET}